### ISSUE TITLE
Bootstrap 4 integration and starting patterns (typog, grid, cards, jumbotron, etc)

### ISSUE THREAD

**Issue by jcar3488** [phase2/particle#111]
Install Bootstrap 4 via NPM and any unmet dependencies (i.e., you will need to also install popper.js)

`npm install bootstrap@4.0.0-beta --save`

`npm install popper.js@^1.11.0 --save`

Starting patterns should live inside the /demo folder of their respective atomic-level parent folder (i.e., inside base, atoms, etc). Patterns should include a base pattern twig file with header notes and declaration of data variables, Sass file, JS file, MD file. See https://getbootstrap.com/docs/4.0/getting-started/webpack/ for Bootstrap with Webpack usage.

See the Adventist repo for a proper example of how we set these up with naming conventions if you'd like to see an example (https://bitbucket.org/phase2tech/adventist/src/7cc306fccd4bb96f15641f4741e9f47bdfc052e1/src/themes/ahs_theme/source/_patterns/?at=develop) and how the patterns are displayed in Pattern Lab, https://qa-adventist.ci2.p2devcloud.com/themes/custom/ahs_theme/pattern-lab/public/.

This list is still being completed, but safe to start with what is here.

Layout:

- [x] Containers (applicable variant examples)
- [x] Grids (applicable variant examples)
- [x] Media Object

Content:

- [ ] TBD

Components:

- [x] Breadcrumb
- [x] Buttons (applicable variant examples)
- [x] Card (applicable variant examples)
- [x] Carousel
- [x] Collapse - Accordion example, using Card
- [x] Jumbotron (applicable variant examples)
- [x] Navs - Tabs w/ Javascript behavior; Vertical?
- [x] Pagination
- [ ] Popover

Utilities:

- [x] Borders
- [x] Colors
- [x] Spacing

**Comment by tjheffner** [comment]
i think we can safely say bootstrap 4 has been integrated
