### ISSUE TITLE
All patterns should follow the new "demo" structure

### ISSUE THREAD

**Issue by illepic** [phase2/particle#125]
Nearly every pattern should follow this folder structure. 

```
02-molecules/
  |-- card
    _card.twig
    |-- demo
      card-large.twig
      card-large.yml
      card-dark.twig
      card-dark.yml
      card-no-image.twig
      card-no-image.yml
```

This allows purely demonstration patterns to live in a folder than can be optionally removed from deployment to production. The idea being that anything in `demo` will **not** be included in any other pattern.

What if you **want** to use a pre-loaded pattern usable elsewhere? Simple, just include the re-usable patterns at the top pattern level with some side-car data, ie:

```
02-molecules/
  |--card
    _card.twig
    card-large.twig # This embeds _card.twig with some hardcoded variant values
    card-large.yml
    |--demo
      card-dark.twig
      card-dark.yml
      card-no-image.twig
      card-no-image.yml
```

**Comment by tjheffner** [comment]
https://github.com/phase2/particle/pull/257
