### ISSUE TITLE
Add node dependencies via `engines` key on package.json

### ISSUE THREAD

**Issue by grayside** [phase2/particle#136]
Package.json supports an `engines` key which allows declaring required versions of node and npm. With the change being explored in #135, it seems like clarifying things by calling for Node 6 or Node 8 would be helpful. It will also more quickly flag a problem with a build environment so developers doing initial setup on a project will see they need to switch from an older version of node.

**Comment by illepic** [comment]
Node v8 is the next LTS and PL v10 probably won't sit on an actual project before December, so I'm cool calling for a Node v8 "engine" key.

**Comment by geoff-winner** [comment]
https://docs.npmjs.com/files/package.json#engines
