### ISSUE TITLE
Add Faker Twig Function

### ISSUE THREAD

**Issue by jryanconklin** [phase2/particle#137]
See Issue on [php twig edition](https://github.com/pattern-lab/edition-php-twig-standard/issues/7) for bones of Twig function using Faker. Adapting this would use of Faker within Twig as:

```
{{ faker('property', 'options' }}
```

This is likely impacted by the issues currently in [`pattern-lab/plugin-php-faker`](https://github.com/pattern-lab/plugin-php-faker/issues). For example, when working with this as `{{ faker('ImageUrl', 200, 200)  }}`, only the first argument is honored, returning: `https://lorempixel.com/200/480/?57256`. Note there is an open PR for plugin [issue #4](https://github.com/pattern-lab/plugin-php-faker/issues/4)

**Comment by illepic** [comment]
@jryanconklin do we want to leave this open?

**Comment by jryanconklin** [comment]
No, let’s go ahead and close it.
