### ISSUE TITLE
Consolidate, cleanup, throwaway files in _data/

### ISSUE THREAD

**Issue by illepic** [phase2/particle#157]
_data folder needs some serious attention. All unused info should be tossed.

**Comment by tjheffner** [comment]
cleanup started here, still needs work/evaluation of what data is actually being used. https://github.com/phase2/particle/pull/257

both .json files stay [auto-generated]
device_widths.yml stays
imageStyles.yml stays [we should be consistent on casing, so deviceWidths]

tables/texts/times are all nice helpers but not sure if anything actually uses them

data.yml needs cleaned up [should keep global pl nav/footer, some other things, but can be reduced heavily]

listItems needs simplified/cleaned/nuked if nothing uses it
