### ISSUE TITLE
Make "intro" base pattern, set as default starting point

### ISSUE THREAD

**Issue by illepic** [phase2/particle#159]
Explanation and guidance, link to docs, etc.

**Comment by tjheffner** [comment]
this is a good example to follow / what we're envisioning. add links to our docs as well
https://standards.usa.gov/design-principles/ 

the line in config that needs to be updated:
https://github.com/phase2/particle/blob/epic/v10/apps/pl/pattern-lab/config/config.yml#L24

**Comment by tjheffner** [comment]
this is done, astrogoat lives
