### ISSUE TITLE
Yeoman generator for new component

### ISSUE THREAD

**Issue by illepic** [phase2/particle#161]
As we coalesce around a component shape, we need a yeoman generator that provides the basics:

- _component.twig, starts with `.component` block class
- _component.scss, starts with `.component` block class
- index.js, starts with js module structure of project
- demo/component-demo.twig
- demo/component-demo.yml
- demo/component-demo.md

**Comment by tjheffner** [comment]
handled here: https://github.com/phase2/particle/pull/266
