### ISSUE TITLE
Enable/disable webpack features based on prod/dev flags.

### ISSUE THREAD

**Issue by illepic** [phase2/particle#163]
We want heavier/lighter processing based on if we're actively developing or if we're building for production.

**Comment by tjheffner** [comment]
this example is slightly outdated from uarts, but cross-env should make this a breeze:

env vars defined inside of package.json dev/build commands
https://github.com/tjheffner/drupal-vue-menu/blob/master/package.json

prod env var checked inside of webpack config, extra settings applied
https://github.com/tjheffner/drupal-vue-menu/blob/master/webpack.config.js

**Comment by grayside** [comment]
I'm surprised the whole toolchain is otherwise windows compatible such that we would need cross-env. None of out other tools balk at env vars.

**Comment by tjheffner** [comment]
cross-env was totally not needed, and webpack prod/dev splits handle different features now. closing
