### ISSUE TITLE
Notes in README about starting from scratch

### ISSUE THREAD

**Issue by illepic** [phase2/particle#178]
Note on removing imports from `design-system.js`

**Comment by tanc** [comment]
I'm currently going through the process of stripping everything back so as to be able to use our own components. Is there any more documentation on doing this? One of the first things I've discovered is the design-system.js file throwing lots of errors.

**Comment by tjheffner** [comment]
There are not docs for that yet, but this is a good reminder that we should get some info in there soon. sorry. The most updated current docs for Particle can be found here: https://phase2.github.io/frontend-docs/

here's a rough walkthrough of how i would start from basically scratch:
1. delete pretty much every component in `source/_patterns`, only keep things in 00-protons (we'll come back to them) and the top-level namespace folders themselves (01-atoms, etc)
2. remove/comment out every `import * as foo from 'pattern/foo;'` in `source/design-system.js` & the var name inside `components = {}`
3. if intended for a drupal theme, nuke the `apps/drupal/templates` folder (or all the .html.twig templates in the subfolders). Easier to just start those from scratch later than untangling which components you kept/would replace things with. Some theme suggestions have been added inside of particle.theme, but that file can be pruned also (don't delete it, just everything in it after the filedoc comment).

4. Coming back to 00-protons, this is the trickiest part, depending on how much bootstrap code you'd like to keep. You'll need to check inside the different `00-protons/*/_.scss` files and determine which pieces, if any, you're still using. Personally I keep bootstrap's reboot, mixins (breakpoint queries), sometimes the grid system, root & variables (contains the bootstrap color system helpers plus other sass maps that Pattern Lab makes use of for demo patterns). This does not result in a noticeably bloated bundle, in my experience.

If you're not keeping _any_ of bootstrap, do note you will need to update some variables inside of `particle/apps/pl/scss/_scss2json.scss`, which are used to export Sass values to a .json file ( `source/_data/scssVariables.json`). That file is used to populate some of the demo patterns inside of `00-protons/demo`.

And that's pretty much it, I think. Once stripped down to your liking, new components should still be created/added as normal (`npm run new` for convenience), in a namespaced folder (`01-atoms/foo`) with their own index.js importing their assets and added to design-system.js.

**Comment by tanc** [comment]
Fantastic reply, thank you! This is basically what I'd already done with a few extra useful bits of info.

I'm trying to use Tailwind instead of Bootstrap and I need to be able to add a Tailwind import late in the webpack build. Can you advise how I would add a single sass partial as one of the last items?

**Comment by tjheffner** [comment]
@tanc Depends on how late you need it imported. I haven't used Tailwind personally, but it looks like you'll need to add a small piece to the postcss portion of webpack config (look in `webpack.particle.dev.js`) https://tailwindcss.com/docs/installation/#webpack and then you can import whatever partial you need using `@tailwind/foo`. https://tailwindcss.com/docs/installation/#3-use-tailwind-in-your-css

For most node_module css, it can be imported the same as bootstrap, `@import ~module_name/path/to/scss/partial;`

As for importing late in the webpack build, it's really up to you when/where your styles get included. Everything used needs to end up in the .js chain eventually (e.g. tailwind @imported into your sass file, and then that sass file imported in some index.js). Depending on what components are going to rely on the tailwind CSS, you may want to include it in 00-protons (where we put bootstrap by default), a later component, design-system.js, or even one of the app-specific entry points (e.g. `apps/drupal/index.js`)
