### ISSUE TITLE
Move pa11y and backstop deps to testDependencies key on package.json

### ISSUE THREAD

**Issue by illepic** [phase2/particle#180]
In README.md you just mention, copying from `testDependencies` to `devDependencies` and running `npm install` and then the proper command.

**Comment by grayside** [comment]
Note that yarn does not currently support `testDependencies`, at least from a review of documentation.

**Comment by illepic** [comment]
Noting here that this really isn't a concept to npm/yarn. I think the best thing we can do is add words to the docs about installing testing frameworks and provide preconfiguration (like pa11y)
