### ISSUE TITLE
Clicking carousel control arrows skips page down to that element

### ISSUE THREAD

**Issue by illepic** [phase2/particle#193]
At http://localhost:8080/pl/?p=molecules-carousels, clicking a Carousel control arrow jumps the page down.

**Comment by illepic** [comment]
Noting here: this is only an issue when inside a PL iframe. Just update the demo to include a little info message atom that warns of this.

**Comment by jryanconklin** [comment]
PR: https://github.com/phase2/particle/pull/197

**Comment by tjheffner** [comment]
this has been fixed for a minute
