### ISSUE TITLE
All demo pages should extend container grid instead of embed

### ISSUE THREAD

**Issue by illepic** [phase2/particle#194]
The demo pages have the luxury of only needing to extend the grid and override blocks instead of embedding the grid and using `with`.

Convert all demo pages to use `extend`, like https://github.com/phase2/particle/pull/190/files#diff-e8a101dd8224a3aa7149b9b95bfa3713

**Comment by jryanconklin** [comment]
PR in for this, see https://github.com/phase2/particle/pull/198

**Comment by tjheffner** [comment]
this has been fixed for a minute
