### ISSUE TITLE
Certain cards in the card demo are broken

### ISSUE THREAD

**Issue by illepic** [phase2/particle#195]
![2017-12-18 at 15 56](https://user-images.githubusercontent.com/295127/34133873-15850914-e40c-11e7-8998-4feaaaf1c1c3.png)
![2017-12-18 at 15 57](https://user-images.githubusercontent.com/295127/34133876-1cb363d4-e40c-11e7-9636-99e85ee096b5.png)

**Comment by rloos289** [comment]
This is actually a deliberate use of the `card-flush` class. Probably want to move it somewhere else since it doesn't look great
