### ISSUE TITLE
Particle Alpha feedback 

### ISSUE THREAD

**Issue by illepic** [phase2/particle#203]
Tobby feedback:

- Subtheme does not work
- [ ]  Need docs on the fact this is **NOT** a subtheme, it is a STARTER theme
- [ ]  Need docs on how to rename for a drupal theme
- [x]  the docs url needs docs
- [ ]  Downloading `drush dl` vs `composer require` to get `components` module
- [x]  Messages set in `.theme`
- [ ]  Move drupal/grav/pl specific stuff to readme at root of `/app/thing`
- [x]  Docs on how to make a new "app"

**Comment by grayside** [comment]
Riffing on "starter not subtheme":

1. What if a project needs a variant on the design system? Does that require two particle instances where #2 does fancy namespacing?
2. What if a project is fine with a single design system, but needs variations in the themes. Use case example: Site factory in which theme selection is a Skin or Layout Chooser.

**Comment by illepic** [comment]
I think this just became a much larger discussion around "variations" or "versions" or "multiple implementations" of a design system in, say, a Drupal theme.

This is much larger than the initial scope of the project, so we'll need to discuss how this fits into beta release.

**Comment by illepic** [comment]
Bloom opinion: there is ONE design system. Period. The canonical design system holds the variations (and demonstrates these in PL). Variations are usually CSS changes on shared markup, ie body class of `theme--dark` changes all `card` molecule styles to the "dark background/light text" or whatever.

**Comment by jryanconklin** [comment]
"Messages set in `.theme`" dealt with in PR #201.

**Comment by tjheffner** [comment]
docs url now contains 50% more words. docs on adding/removing apps covered. https://phase2.github.io/frontend-docs/
