### ISSUE TITLE
Move demo folders into PL app

### ISSUE THREAD

**Issue by illepic** [phase2/particle#208]
Can the PL app hold the PL folder structure required for the UI and demos, while source stays clean?

**Comment by illepic** [comment]
`_twig-components` needs to be massively re-evaluated for NO use in design system.

**Comment by tjheffner** [comment]
https://github.com/phase2/particle/pull/257

PL app is globbing demos as of that PR, separately from the design system... so halfway there. Possibly re-evaluate whether demos need to be fully isolated like this [personally I like how they're subfoldered in the components they're demoing]

**Comment by jryanconklin** [comment]
@illepic Do you consider this still an issue? This would likely solve some of our issues (but be a painful dev experience).

That said, I imagine this is how we'd roll `stories` if implementing Storybook as an alternative. Consider including for 10.4.

**Comment by madhaze** [comment]
I like having the demo/stories with the component. Seems like you would have to duplicate the folder structure in App/pl to match that of the design system.

**Comment by illepic** [comment]
Now that we're moving twig files to `dist/` for use within Drupal, we don't care what's left in `/source`. Closing.
