### ISSUE TITLE
Theme Colors Overrides Crash Pattern Lab App

### ISSUE THREAD

**Issue by jryanconklin** [phase2/particle#218]
When working with the `$theme_colors` and Bootstrap 4 color overrides in `source/_patterns/00-protons/non-printing/_colors.scss`, Pattern Lab becomes unresponsive in the browser. This makes it necessary to close and re-open the browser on making colors changes.

**Comment by illepic** [comment]
This is solved since we moved to Webpack handling all static dev server handling doing hot injection of chunks instead of ExtractText generating css every time.
