### ISSUE TITLE
Adopt a Twig Coding Standard & Update Readme

### ISSUE THREAD

**Issue by cybtachyon** [phase2/particle#225]
Suggesting that the Readme be updated with a specific Twig Standard a-la AirBnB's JS standard.

Examples:
http://twig.sensiolabs.org/doc/coding_standards.html
https://www.drupal.org/node/1823416
https://github.com/cybtachyon/twig-standards (Superset of the above)

Adding in a twig linter such as https://github.com/asm89/twig-lint to the build process may also be useful.

**Comment by illepic** [comment]
https://github.com/phase2/particle/pull/395
