### ISSUE TITLE
Pattern Lab empty after start on WIndows (node-gyp errors)

### ISSUE THREAD

**Issue by peterhebert** [phase2/particle#228]
Hi,

I've been having issues getting Particle up and runnin on Windows 10, with PHP 7.2.2, node 8.9.4 / npm 5.6.0 and Composer 1.3.0

When I run `npm install` I get the following errors:
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Peter\AppData\Local\Programs\Python\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Peter\development\particle-epic-v10\node_modules\weak
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

After running `npm start`, it seems to run the webpack build successfully (I get message 'webpack: Compiled successfully.'), but going to localhost:8080/pl results in:

NOTHING HERE YET
PLEASE GENERATE YOUR SITE BEFORE TRYING TO VIEW IT.

Seems like it's looking for a Python executable... not sure what's going on... Seems to be related to the node-gyp package. Going to the project page for [node-gyp](https://github.com/nodejs/node-gyp) seems to indocate that you need to globally install [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) in order to use node-gyp:

`npm install --global --production windows-build-tools`

After doing this, I ran `npm install` again, and the node-gyp errors went way. However, the Pattern Lab still doesn't generate properly, again with webpack saying that it compiled successfully.

**Comment by peterhebert** [comment]
Noticed that I'm getting a whole bunch of errors `Entrypoint undefined = extract-text-webpack-plugin-output-filename` when trying to run `npm run compile:pl`

Here is the complete output:

	> Particle@10.0.0 compile:pl C:\Users\Peter\development\particle-epic-v10
	> webpack --display-entrypoints --config webpack.pl.config.js && gulp compile

	[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/Peter/development/particle-epic-v10/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
	Hash: 30eb09671315864725e1
	Version: webpack 3.10.0
	Time: 20269ms
													   Asset       Size  Chunks                    Chunk Names
				   logo.svg?35d56001f631f256cac5758fa7655b6c  503 bytes          [emitted]
								  favicons/favicon-32x32.png    1.36 kB          [emitted]
										favicons/favicon.ico    33.3 kB          [emitted]
											 favicons/.cache  522 bytes          [emitted]
	fontawesome-webfont.svg?912ec66d7572ff821749319396470bde     444 kB          [emitted]  [big]
			  astrogoat.png?aca65e8fcaed9e82e97b5bb00143a6ef    44.7 kB          [emitted]
								  favicons/favicon-16x16.png  571 bytes          [emitted]
												   app-pl.js    1.08 MB       0  [emitted]  [big]  app-pl
												  commons.js    5.82 kB       1  [emitted]         commons
										   app-pl.styles.css    1.12 MB       0  [emitted]  [big]  app-pl
											   app-pl.js.map    1.28 MB       0  [emitted]         app-pl
									   app-pl.styles.css.map     409 kB       0  [emitted]         app-pl
											  commons.js.map    5.85 kB       1  [emitted]         commons
	Entrypoint app-pl [big] = commons.js commons.js.map app-pl.js app-pl.styles.css app-pl.js.map app-pl.styles.css.map
	[./apps/pl/index.js] ./apps/pl/index.js 1.72 kB {0} [built]
	[./apps/pl/scss/_scss2json.scss] ./apps/pl/scss/_scss2json.scss 310 bytes {0} [built]
	[./apps/pl/scss/_styleguide.scss] ./apps/pl/scss/_styleguide.scss 310 bytes {0} [built]
	[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 823 bytes {0} [built]
	[./source/_patterns/01-atoms/grid/index.js] ./source/_patterns/01-atoms/grid/index.js 311 bytes {0} [built]
	[./source/_patterns/01-atoms/image/demo/astrogoat.png] ./source/_patterns/01-atoms/image/demo/astrogoat.png 92 bytes {0} [built]
	[./source/_patterns/01-atoms/image/demo/index.js] ./source/_patterns/01-atoms/image/demo/index.js 67 bytes {0} [built]
	[./source/_patterns/02-molecules/jumbotron/index.js] ./source/_patterns/02-molecules/jumbotron/index.js 434 bytes {0} [built]
	[./source/_patterns/02-molecules/nav/index.js] ./source/_patterns/02-molecules/nav/index.js 382 bytes {0} [built]
	[./source/_patterns/02-molecules/pagination/index.js] ./source/_patterns/02-molecules/pagination/index.js 410 bytes {0} [built]
	[./source/_patterns/03-organisms/accordion/index.js] ./source/_patterns/03-organisms/accordion/index.js 476 bytes {0} [built]
	[./source/_patterns/03-organisms/article/index.js] ./source/_patterns/03-organisms/article/index.js 377 bytes {0} [built]
	[./source/_patterns/05-pages/homepage/index.js] ./source/_patterns/05-pages/homepage/index.js 887 bytes {0} [built]
	[./source/design-system.js] ./source/design-system.js 2.51 kB {0} [built]
	   [0] multi ./apps/pl/index.js 28 bytes {0} [built]
		+ 76 hidden modules
	Child favicons-webpack-plugin for "source\_data\favicons-stats.json":
							 Asset       Size  Chunks             Chunk Names
		favicons/favicon-32x32.png    1.36 kB          [emitted]
		favicons/favicon-16x16.png  571 bytes          [emitted]
			  favicons/favicon.ico    33.3 kB          [emitted]
				   favicons/.cache  522 bytes          [emitted]
		 + 1 hidden asset
		Entrypoint undefined = C:\Users\Peter\development\particle-epic-v10\source\_data\favicons-stats.json
		[./node_modules/favicons-webpack-plugin/lib/favicons.js?{"outputFilePrefix":"favicons/","icons":{"android":false,"appleIcon":false,"appleStartup":false,"coast":false,"favicons":true,"firefox":false,"opengraph":false,"twitter":false,"yandex":false,"windows":false},"background":"#fff","persistentCache":true,"appName":"Webpack App"}!./source/_patterns/01-atoms/image/logo.svg] ./node_modules/favicons-webpack-plugin/lib/favicons.js?{"outputFilePrefix":"favicons/","icons":{"android":false,"appleIcon":false,"appleStartup":false,"coast":false,"favicons":true,"firefox":false,"opengraph":false,"twitter":false,"yandex":false,"windows":false},"background":"#fff","persistentCache":true,"appName":"Webpack App"}!./source/_patterns/01-atoms/image/logo.svg 420 bytes {0} [built]
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!apps/pl/scss/_styleguide.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./apps/pl/scss/_styleguide.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./apps/pl/scss/_styleguide.scss 9.36 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/01-atoms/image/_image.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/image/_image.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/image/_image.scss 40.5 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/01-atoms/grid/_grid.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/grid/_grid.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/grid/_grid.scss 75.9 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!apps/pl/scss/_scss2json.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./apps/pl/scss/_scss2json.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./apps/pl/scss/_scss2json.scss 1.92 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/01-atoms/alert/_alert.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/alert/_alert.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/alert/_alert.scss 47.9 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/01-atoms/branding/_branding.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/branding/_branding.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/branding/_branding.scss 260 bytes {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/01-atoms/breadcrumb/_breadcrumb.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/breadcrumb/_breadcrumb.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/breadcrumb/_breadcrumb.scss 39.6 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/01-atoms/icon/scss/_icon.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/icon/scss/_icon.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/icon/scss/_icon.scss 37.8 kB {0} [built]
		[./source/_patterns/01-atoms/icon/font/iconfont.eot] ./source/_patterns/01-atoms/icon/font/iconfont.eot 3.21 kB {0} [built]
		[./source/_patterns/01-atoms/icon/font/iconfont.eot?cachebust=54566] ./source/_patterns/01-atoms/icon/font/iconfont.eot?cachebust=54566 3.21 kB {0} [built]
		[./source/_patterns/01-atoms/icon/font/iconfont.ttf] ./source/_patterns/01-atoms/icon/font/iconfont.ttf 2.96 kB {0} [built]
		[./source/_patterns/01-atoms/icon/font/iconfont.woff] ./source/_patterns/01-atoms/icon/font/iconfont.woff 1.99 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/01-atoms/dropdown/_dropdown.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/dropdown/_dropdown.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/dropdown/_dropdown.scss 59.6 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/01-atoms/button/_button.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/button/_button.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/button/_button.scss 75 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/02-molecules/nav/_nav.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/02-molecules/nav/_nav.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/02-molecules/nav/_nav.scss 43.8 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/02-molecules/card/_card.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/02-molecules/card/_card.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/02-molecules/card/_card.scss 58.4 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/01-atoms/list-group/_list-group.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/list-group/_list-group.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/list-group/_list-group.scss 54.4 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/02-molecules/carousel/_carousel.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/02-molecules/carousel/_carousel.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/02-molecules/carousel/_carousel.scss 52 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/02-molecules/pagination/_pagination.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/02-molecules/pagination/_pagination.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/02-molecules/pagination/_pagination.scss 44.2 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/02-molecules/example-widget/_example-widget.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/02-molecules/example-widget/_example-widget.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/02-molecules/example-widget/_example-widget.scss 266 bytes {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/02-molecules/jumbotron/_jumbotron.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/02-molecules/jumbotron/_jumbotron.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/02-molecules/jumbotron/_jumbotron.scss 42.8 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/03-organisms/accordion/_accordion.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/03-organisms/accordion/_accordion.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/03-organisms/accordion/_accordion.scss 261 bytes {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/03-organisms/article/_article.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/03-organisms/article/_article.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/03-organisms/article/_article.scss 259 bytes {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/03-organisms/navbar/_navbar.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/03-organisms/navbar/_navbar.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/03-organisms/navbar/_navbar.scss 66.6 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/01-atoms/badge/_badge.scss:
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/badge/_badge.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/01-atoms/badge/_badge.scss 44.1 kB {0} [built]
			+ 1 hidden module
	Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-3!node_modules/postcss-loader/lib/index.js??postcss!node_modules/sass-loader/lib/loader.js??ref--0-5!source/_patterns/00-protons/_base.scss:
														   Asset    Size  Chunks                    Chunk Names
		fontawesome-webfont.svg?912ec66d7572ff821749319396470bde  444 kB          [emitted]  [big]
		Entrypoint undefined = extract-text-webpack-plugin-output-filename
		[./node_modules/css-loader/index.js?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib/index.js?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/00-protons/_base.scss] ./node_modules/css-loader?{"importLoaders":1,"sourceMap":true}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss"}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true,"functions":{}}!./source/_patterns/00-protons/_base.scss 477 kB {0} [built]
			+ 7 hidden modules
	C:\Users\Peter\development\particle-epic-v10\apps\pl\pattern-lab
	[10:56:36] Using gulpfile ~\development\particle-epic-v10\gulpfile.js
	[10:56:36] Starting 'compile'...
	[10:56:36] Starting 'compile:twig-namespaces'...
	[10:56:36] Finished 'compile:twig-namespaces' after 105 ms
	[10:56:36] Starting 'compile:pl'...
	configuring pattern lab...
	Twig file not found: @atoms/_grid-2-up.twig


	[10:56:37] Finished 'compile:pl' after 714 ms
	[10:56:37] Finished 'compile' after 823 ms

**Comment by illepic** [comment]
Since you now have Python working on Windows, can you verify that the JS and CSS file are generating into `dist/assets`?

The PL build step is separate, so can you re-run `npm run setup && npm run compile:pl`.

**Comment by illepic** [comment]
@peterhebert it's been almost 2 months, closing this down soon.

**Comment by illepic** [comment]
We've moved to a new icons system in v10, let me know if this works for you.
