### ISSUE TITLE
Update stylelint plugin to new version

### ISSUE THREAD

**Issue by illepic** [phase2/particle#264]
https://www.npmjs.com/package/easy-stylelint-plugin should solve our style linting

**Comment by tjheffner** [comment]
noting here that our current style linting is almost webpack 4 compatible, just waiting on one PR to get merged, pending agreement to a license. hooray open source: https://github.com/webpack-contrib/stylelint-webpack-plugin/pull/140

we'll also want to look into swapping extract-text-webpack-plugin to https://github.com/webpack-contrib/mini-css-extract-plugin , the webpack4 successor

**Comment by illepic** [comment]
Getting closer: latest master updated to a PR branch specifically for webpack 4, will 🎉 when it's merged:

https://github.com/webpack-contrib/stylelint-webpack-plugin/pull/144

**Comment by illepic** [comment]
Solved here: https://github.com/phase2/particle/pull/274
