### ISSUE TITLE
Guidance/support for running yeoman in containers

### ISSUE THREAD

**Issue by grayside** [phase2/particle#272]
Yeoman has some special requirements in order to be run that aren't compatible with most "default" containers you might use.

Outrigger has a Docker image that can be used to facilitate running the Yeoman generator, see the README for details: https://github.com/phase2/docker-yeoman

The new outrigger/node image **might** be potentially compatible with some minor tweaks and docs. outrigger/build is not.

**Comment by illepic** [comment]
https://github.com/yeoman/yo/issues/348
