### ISSUE TITLE
Looking for recommended approach to use with a custom component library

### ISSUE THREAD

**Issue by tanc** [phase2/particle#277]
We're currently using a forked version of this repo as a basis for building our starterkit theme to be used in-house for our client's sites. I'd really like to be able to use Particle as is without having to maintain a fork and I'm looking for ideas on how to approach integrating a set of potentially optional components with Particle.

Ideally I'd have a component library available that designers and front end developers can choose from and add to Particle. Is this something you do internally at Phase2? Or do you always craft everything from scratch and use Particle as a starting point?

Any ideas on this kind of workflow would be most helpful!

**Comment by LegendT** [comment]
We are in a similar situation and so I too would be interested in hearing any ideas. We're currently looking at using Bit (bitsrc.io) as the component repo and Particle for the Drupal integration and pattern lab.

**Comment by himerus** [comment]
I'm curious as well. I haven't had a terrible amount of time to dig into the internals and plan out a true roadmap for using on my next project(s0, but the ideal scenario as I see it would meet the following requirements:

- Use Particle without forking or modifying.
  - Require via `npm i phase2/particle` 
  - Build 'particle instance' by running `npm build particle-instance` 
    - This creates the 'working' installation of Particle in the project environment.
- Host/Maintain a custom set of Protons/Atoms/Organisms/etc (elements) in an external repo attached/associated with the project the Particle instance is being utilized with. 
- Disable certain Protons/Atoms/Organisms/etc provided by Particle 
  - This would be via config with Particle living in node_modules.
  - As config in the custom 'particle instance'?
- Possibly even with spit config & element 'groups' that would allow separately maintained groups of elements such as
  - Shared elements
  - Article elements
  - Mapping elements
  - etc. (I'm just thinking how I'd split up 'modules' in Drupal for reuse later)

**Comment by jryanconklin** [comment]
Particle as-is is used as a starter kit, e.g, we clone it and use a new version each time. The direction for 11 will be much as himerus notes above, but likely a bigger lift than we can do in the short term. The work for 10.4 -- updating this repo to Node PL 3 in #577 will clear the way here.

But for the time being, it's probably best to consider Particle being it's own thing after an individual clone or fork of the project.
