### ISSUE TITLE
Clarify best way to add custom fonts

### ISSUE THREAD

**Issue by p51i** [phase2/particle#281]
Can the docs provide some guidance or an example of the "best-practice" method for adding/importing font files?

**Comment by tjheffner** [comment]
thank you for the feedback! we will get some docs on font management up soon as well.

in the meantime, our "best practice" is essentially:

1. put font files into `particle/source/fonts` [this folder doesn't exist by default]
2. setup font-faces as normal in your stylesheets. you might set font family variables inside of `/00-protons/_variables.scss` or override bootstrap's font families inside of `/00-protons/printing/_type.scss`

You can see an example of this in the iconfont structure inside of `source/_patterns/01-atoms/icon/scss/_icon.scss` (note this font face is using a component-specific font directory, not the top-level `source/fonts`)

If you're using webfonts you might be able to get away without setting font-faces explicitly.

**Comment by illepic** [comment]
@coraunderhill, you can see we need to make this clearer.

**Comment by illepic** [comment]
https://github.com/phase2/particle/issues/408

**Comment by illepic** [comment]
The new protons organization in 10.1 includes both remote and local font examples.
