### ISSUE TITLE
npm 6 and node 10 compatibility check

### ISSUE THREAD

**Issue by illepic** [phase2/particle#288]

**Comment by cleverington** [comment]
Tried via `10.1.0` and received a number of errors, which appeared to be rooted in font-awesome and deprecations.

![deprecation_errors](https://user-images.githubusercontent.com/1015474/40092347-88ce9832-5882-11e8-842e-342f2a4397eb.png)

**Comment by illepic** [comment]
Node 6 - 10 now supported.
