### ISSUE TITLE
Module build failed: SyntaxError

### ISSUE THREAD

**Issue by edysmp** [phase2/particle#289]
For some reason I get errors  using platform.sh hosting.

Error example:
```ERROR in ./node_modules/bootstrap/js/src/carousel.js
Module build failed: SyntaxError: /app/web/themes/particle/node_modules/bootstrap/js/src/carousel.js: Support for the experimental syntax 'objectRestSpread' isn't currently enabled (217:9):

215 |     _getConfig(config) {
  216 |       config = {
    > 217 |         ...Default,
|         ^
  218 |         ...config
  219 |       }
  220 |       Util.typeCheckConfig(NAME, config, DefaultType)

  Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section of your Babel config to enable transformation.
```

# Posible solution.
It seem like is not recognizing the .babelrc. I did this code and works.
```index 29d3e52..aa45b2a 100755
--- a/web/themes/particle/webpack.particle.dev.js
+++ b/web/themes/particle/webpack.particle.dev.js
@@ -69,6 +69,13 @@ module.exports = {
  exclude: /node_modules\/(?!(bootstrap)\/).*/,
  use: {
    loader: 'babel-loader',
  +          options: {
  +            presets: ['@babel/preset-env'],
    +            plugins: [
    +              '@babel/plugin-proposal-object-rest-spread',
    +              '@babel/plugin-proposal-class-properties'
    +            ]
  +          }
},
},
{
```

**Comment by illepic** [comment]
Can you verify that platform.sh even recognizes "hidden" dotfiles like .babelrc?

**Comment by ellyjonez** [comment]
I am having this issue also, on my local machine upon setting up particle for the first time. Adding `  "@babel/transform-object-rest-spread"` to .babelrc stopped the compile error above, but now I'm getting ```ERROR in ./apps/pl/index.js
Module build failed: Error: Cannot find module '@babel/plugin-transform-object-rest-spread'```

**Comment by tjheffner** [comment]
just ran into this also on a new pull of master locally where the .babelrc was not recognized. moving babel options into the webpack loader config seemed to sort it out [jest tests failed, though not sure if these are related. did not delete .babelrc after moving into webpack)

**Comment by illepic** [comment]
Closing this for now, reopen if it comes up again in v10+
