### ISSUE TITLE
"Nothing to see here"

### ISSUE THREAD

**Issue by Gravitary** [phase2/particle#290]
When accessing http://localhost:8080/pl  , I'm seing the Pattern Lab header saying:

> NOTHING HERE YET
> PLEASE GENERATE YOUR SITE BEFORE TRYING TO VIEW IT.

During npm run start I'm getting the following message during the gulp tasks:
`Twig file not found: @atoms/_grid-2-up.twig`

This happens during the compile:pl gulp task and I verified that the file does indeed exists.
After manually running the task via the command line, I'm getting the same error, so I'm thinking this must be a config issue.
Reinstalling Particle hasn't fixed the issue.

Any ideas?

---

On an extra note:
The Grav Symlinking has worked properly, however I'm not sure on how templates or pages come into play here, as they don't appear in the backend.

**Comment by Gravitary** [comment]
Narrowed the error down:

Deleting the **demo** folders that use grid-2-up and footer solved the issue to a degree.
Now Pattern Lab tries to build but comes up with a list of Symfony errors about the file paths resulting from the PatternLab config

**Comment by tjheffner** [comment]
can you verify that you've run `npm run setup`? that is a one-time command after `npm install` that should initially generate pattern lab and it's dependencies

**Comment by gmaxwell-ed** [comment]
I potentially have the same issue. I'm on Windows. When I first ran `npm run build:pl` I got an error:
`'NODE_ENV' is not recognised as an internal or external command, operable program or batch file.`

In the package.json, I then changed the relevant lines in the "scripts" section to (for example):
    `"build:pl": "SET NODE_ENV='production' gulp compile; webpack --config ./apps/pl/webpack.pl.prod.js",`

This got rid of the error. I ran `npm run setup `again, and then `npm run build:pl` but I still get the "nothing to see here" message in Pattern Lab.

Do we need to install a starterkit before building?

**Comment by illepic** [comment]
Noting here that we'll need to leverage something like https://www.npmjs.com/package/cross-env to achieve true Windows compatibility.

In the meantime, I highly, highly, highly suggest WSL (https://docs.microsoft.com/en-us/windows/wsl/install-win10). As a matter of fact, a majority of Particle development was done on WSL and it works absolutely perfectly.

**Comment by illepic** [comment]
This is now in v10.1 via `cross-env`:

https://github.com/phase2/particle/pull/372
