### ISSUE TITLE
new contrib theme based on particle

### ISSUE THREAD

**Issue by alianov** [phase2/particle#294]
Hi, 

I would like to create a slim version of particle, a Drupal8 theme that will be based on particle stack.
Why is it needed? Particle has a high learning curve, you have to master PL, webpack and a bunch of other frontend frameworks. I would like to create a theme that will have:
1. PL 
2. bootstrap
3. gulp

**Comment by illepic** [comment]
Hi @alianov! Can you clarify your question: are you asking what the technical requirements for Particle are?

[The updated Readme has a pretty good description of the requirements.](https://github.com/phase2/particle#prerequisites)

**Comment by jryanconklin** [comment]
Closing this issue.
