### ISSUE TITLE
Opening Bootstrap link in Pattern Lab breaks internal navigation

### ISSUE THREAD

**Issue by dslemay** [phase2/particle#318]
Clicking a link to visit the Bootstrap documentation within Pattern Lab currently navigates within the tab. However, this breaks the ability to navigate back from the documentation to Pattern Lab without a hard refresh. There is a console error.

![Console Error in Pattern Lab](https://user-images.githubusercontent.com/26767995/41549110-a2fb75f6-72d9-11e8-9715-fd73f456124b.png)

I would propose converting over these links to use `target="_blank" rel="noopener noreferrer"` to open the links in a new tab to circumvent this issue.

**Comment by illepic** [comment]
Sounds great! Hit it.
