### ISSUE TITLE
Implement Webpack Bundle Analyzer

### ISSUE THREAD

**Issue by jryanconklin** [phase2/particle#389]
Investigate and determine whether Webpack Bundle Analyzer is appropriate for Particle:

https://github.com/webpack-contrib/webpack-bundle-analyzer

**Comment by illepic** [comment]
Noting here that I got Webpack Bundle Analyzer running with no code changes with just:

```bash
NODE_ENV=production npx webpack --config apps/pl/webpack.pl.js --profile --json > stats.json
npx webpack-bundle-analyzer stats.json
```
