### ISSUE TITLE
License

### ISSUE THREAD

**Issue by evanmwillhite** [phase2/particle#40]
First off, 😍 . Seeing this evolve from DrupalCon is awesome, and I love the combination of the pattern lab organization with the extend/include twig approach.

Since this appears to be something available to the community, what are you thinking [in terms of license](https://help.github.com/articles/open-source-licensing/)?

**Comment by illepic** [comment]
PR here: https://github.com/phase2/pattern-lab-starter/pull/96

**Comment by illepic** [comment]
Needs backport to v9.
