### ISSUE TITLE
glob.js isn't watching for changes in the /source/_data/ directory

### ISSUE THREAD

**Issue by coraunderhill** [phase2/particle#409]
When updating the `00-protons/non-printing/_colors.scss` document with new custom colors, `_scss2json.scss` exports the changes correctly to `scss2json.json` in the `/source/_data` directory, but `/app/pl/glob.js` does not appear to be watching the file (line 18).

**Comment by coraunderhill** [comment]
When renaming a color previously defined in `_colors.scss` you have to modify the associated `.twig` file in the `demo` folder in order to run `build:pl`

**Comment by illepic** [comment]
Quick note: all the demos that come from sass2json only compile out on initial start of Particle, not realtime while coding. All the json generation would cause double-compiles constantly so we've moved it to JUST a startup process for now.

**Comment by illepic** [comment]
Actually brought back the reactivity here: https://github.com/phase2/particle/pull/411
