### ISSUE TITLE
Css stylesheet

### ISSUE THREAD

**Issue by Gwenweb** [phase2/particle#435]
Hi ! I installed particule with Drupal8. I followed the instructions but I must have missed something because, even if my scss (that I added in source/_patterns/) is compile with webpack, it does not appear on my Drupal frontend page.

In the browser console, I have this error :

Refused to apply style from 'http://patparticule.lndo.site/themes/particle/dist/assets/app-drupal.styles.css?pgslok' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Along with : 
Uncaught ReferenceError: jQuery is not defined

An idea of what I did wrong ?

**Comment by Brigette-Eckert** [comment]
Did you include

```import $ from 'jquery' ```
at the top of your index.js file in your pattern folder?

**Comment by Gwenweb** [comment]
Hi Brigette-Eckert,
thanks for your answer.

Yes, my index.js file in the pl folder begins with `import $ from 'jquery';`

**Comment by jryanconklin** [comment]
@Gwenweb, have you compiled Drupal's assets via `npm run build:drupal`? Are you using the Component Library module on your Drupal site?

https://phase2.gitbook.io/frontend/particle/commands

If both of these are correct, would you tell me a bit about your setup?

**Comment by Gwenaweb** [comment]
Hi jryanconklin,
I did used npm run build:drupal and Component Library module.

Here is my repo https://github.com/Gwenaweb/pat-particule if you want to check it out.

Sorry for my late answer, this is a project to explore pattern-lab/particule and can't spend enough time on it. Thanks for you answer !

**Comment by mikecrittenden** [comment]
Looks like your Particle lives in themes/custom/particle but the error message in the issue description is looking for it in themes/particle. Try moving it to themes/particle to see if that fixes the issue. If so, then you should be able to move it back to themes/custom/particle if you prefer it there as long as you update the Particle config to respect that.

**Comment by jryanconklin** [comment]
Assuming the above helped you and closing this issue. Feel free to reopen if you still have an issue.
