### ISSUE TITLE
randomNumber usage should use twig native instead of Faker

### ISSUE THREAD

**Issue by illepic** [phase2/particle#446]
In files like https://github.com/phase2/particle/blob/f8e5f68a942a54941c2e1a167d857556378c0966/source/default/_meta/_00-head.twig#L16, we really don't need to leverage the data.yml file for stuff like that.

**Comment by jryanconklin** [comment]
Note we're currently using `randomNumber(8)` from Faker to generate a random number. This can be replaced with Twig's built-in random function as random(n). Note that Twig renders random numbers differently than Faker, e.g., `random(n)` will return a number between 0 and the integer param whereas Faker's argument is the decimal place values to return.

Files to Change:
* source/default/_patterns/01-atoms/svgicon/_svgicon.twig
* source/default/_meta/_00-head.twig
* source/default/_meta/_01-foot.twig
* source/default/_data/data.yml

Twig Docs for Random:
https://twig.symfony.com/doc/2.x/functions/random.html
