### ISSUE TITLE
Update version to 10.2.0 in package.json

### ISSUE THREAD

**Issue by andriokha** [phase2/particle#459]
Hi, thanks for putting this together! I'm just taking a first look at using it with a Drupal site, and it looks like the version in package.json hasn't been updated with the latest release?

Thanks again!

**Comment by illepic** [comment]
Gah, I've done this on every manual release of 10 so far! We're going to start publishing to NPM as well so will hopefully not be left up to my brain.

@jengrace, if possible for 10.2.X release today please!

**Comment by jengrace** [comment]
@illepic --on it!
