### ISSUE TITLE
Reponsive image pattern

### ISSUE THREAD

**Issue by mrhorse** [phase2/particle#477]
Firstly, @illepic @EvanLovely et al... thanks for the ongoing development of this theme - it really is a superb theme for pattern-led builds, I'm in awe - *especially* when you delve down the rabbit hole and see how well it hangs toegether.... bravo.

I've been working on a D8 patternlab-led build recently, using particle as a base theme. Essentially I amended the tooling workflow to allow us to build components to be used across multiple sites (same client), overriding scss variables depending on the current theme compilation. 

One thing I found lacking was a pattern for producing responsive imgsets. So I made a component to provide this. I find img srcset too limiting due lack of control of which images are displayed at which breakpoints - it's largely up to browser implementation to decide which image is shown where. For this reason my component provides the picture element, where you have full control over what images display at exactly which breakpoint. This means one page image can have many image styles generated... small 1x, small 2x, small 3x, medium 1x..... etc etc. Using twig_tweak modules the image styles are produced at template level. (I don't think the responsive image module available in core is an appropriate way to implement reponsive images - they should be dictated by the front-end, not Drupal config).

I'd love to contribute this back to the project, if this is something you'd be interested in. There's also an accompanying Drupal module to provide Drush commands to audit, import, and delete the responsive styles declared in particle from Drupal, as well as importing selected ymls data from `source/_data` to be globally available in Drupal twig templates.

Let me know your thoughts, if this sounds useful I'll get a MR for you to reivew.

Ta

**Comment by jryanconklin** [comment]
Thank you so much and sorry for the delay in response! I recently updated default images in #570 and have included a very light responsive image approach. If you'd like to add to it, PR is certainly welcome!
