### ISSUE TITLE
Using images

### ISSUE THREAD

**Issue by ghost** [phase2/particle#489]
Hello guys, sorry for my question

but I have really hard time to use my images. We are little company, where we started to using particle, so we are new into this.

I, as front-end, am trying to create slider, something like this:
https://chekromul.github.io/uikit-ecommerce-template/

but I have no idea, how to show images. I created folder in "molecules" called "header-slider" where I created another folder called "images" where I put my images. 

I edited index.js where I added 
`import './images/xxxx.jpg';`

It can compile, but I cant see them. I read doc about it, but I really dont understand it.

Thank you guys

**Comment by luzzardi** [comment]
I'm have probably the same issue.
On our side we are able to see on pattern lab the images using the variable: paths.assets but when we call the organism from a drupal template, that variables is empty and we cannot see the image anymore.

**Comment by Jwaxo** [comment]
Hi @LadIQe and @luzzardi. There are essentially two different ways that images might be used in a pattern, and I want to be clear about it before continuing and potentially directing you in a way you don't appreciate:

# You need the images to be directly embedded into the component itself. The normal instance of that would be when you have one image you want to be distinctly tied to that one component. For example, if you create a molecule named "logo", you'd probably only have one logo, and thus the image would be directly used with the component.
# You need a component that could be re-used with different images. The normal instance of this is when creating a component that, in Drupal's case, would have its images filled with the values of a field. For example, if you have a "photo gallery" node bundle, you would probably wish to create a "carousel" organism component, with *no* defined images, then pass it to Drupal, which would provide the images from the field to fill in the variables.

Both of these require very different solutions! The solution to 1 is the path that luzzardi is looking at, and is further outlined (briefly) in the documentation: https://phase2.gitbook.io/frontend/particle/development/approach#static-images . You need to make sure that the images themselves are included in the bundled assets, which is done via the `import './images/imagename.png'`. Then, in the twig file, use `~paths/assets/imagename.png`.

The solution for 2 is a bit different, and probably the more common use-case. In that case I would create a component that [uses the demo](https://phase2.gitbook.io/frontend/particle/development/using-demos) to place images into your pattern, then load the pattern into Drupal and pass in variables using a preprocess hook. Unfortunately we don't exactly have a step-by-step on how to do that in our docs, but we plan to add one in the near future.

Please let me know if this helped and if I can give any more detailed information, suggestions, or advice.

**Comment by tjheffner** [comment]
if you are using the `paths.assets` route, it should be available to the Drupal side of things. inside `apps/drupal/particle.theme` you'll find a preprocess for that variable. it may need updated to `../../dist/app-drupal/assets/` to match the dist directory structure. (I will make a PR for that here shortly)

**Comment by jryanconklin** [comment]
Images overhauled in #550
