### ISSUE TITLE
Vanilla Particle with DDEV Twig exception

### ISSUE THREAD

**Issue by nonsie** [phase2/particle#501]
Steps to replicate:
1. Set up a basic Drupal 8 site with a content type and primary menu
2. Install latest Particle (git clone git@github.com:phase2/particle.git) and set it as default theme.
3. Load a Drupal page that has primary menu on it

Results in:
PHP message: Uncaught PHP Exception Twig_Error_Loader: "Template "@organisms/navbar/_navbar.twig" is not defined in "themes/custom/particle/apps/drupal/templates/layout/region--primary-menu.html.twig" at line 26.

Note: this site is set up using DDEV but it should not matter since the files match on both.

**Comment by Jwaxo** [comment]
Hey @nonsie, this is not the most uncommon error, and the most likely cause is that Particle + Drupal 8 requires the [Components](https://www.drupal.org/project/components) module for its hand-dandy theme namespacing features.

If that doesn't resolve it, or even if it does, check out the more in-depth D8 steps here to see if you missed anything else: https://phase2.gitbook.io/frontend/particle/getting-started/drupal-8

Let me know if that resolves your issue!

**Comment by illepic** [comment]
Aight, full recreation of the issue:

![image](https://user-images.githubusercontent.com/295127/50565389-318dd900-0ce3-11e9-97c5-062fbed9c2ed.png)

Diving in to tackle it now.

**Comment by illepic** [comment]
PR here:

https://github.com/phase2/particle/pull/502
