### ISSUE TITLE
Implementing detach in the Drupal theme

### ISSUE THREAD

**Issue by Unipro-BysaBoro** [phase2/particle#506]
This is more of a support request/question/clarification type issue.

Implementing this theme for the first time and enjoying it so far :) Slowly working my way through the theme to understand it more. 

In [`apps/drupal/index.js`](https://github.com/phase2/particle/blob/master/apps/drupal/index.js) there is a default behavior: `Drupal.behaviors.designSystem` which currently only declares `attach`. The components themselves however are expected to implement a `disable()` function which presumably maps to `Drupal.detachBehaviors()` (IIUC - looking at existing default components), but I can't find where `disable()` is currently called from. So my question is - Is this happening currently somewhere?

If not then I assume we should be implementing our own custom `detach` on `Drupal.behaviors.designSystem` default behavior then? I couldn't find anything similar to `enableAllComponents` but for disabling/detaching in [`source/default/index.js`](https://github.com/phase2/particle/blob/master/source/default/index.js), would it make sense to add some default `disableAllComponents`/`detachAllComponents` function in there?

I'm more than happy to clarify if anything above doesn't make sense.

**Comment by jryanconklin** [comment]
What you say makes sense and can confirm we don't provide any detaches or implementations of disable. They're there to guide the way, but at least in the default use there hasn't been much of a need to. We mainly approach this project as a starting point. PR welcome if you have come up with something that you're enjoyed!
