### ISSUE TITLE
Namespaces and multiple themes

### ISSUE THREAD

**Issue by juanramonperez** [phase2/particle#511]
I have the requirement to have multiple themes installed at the same time, this cause a collision with the namespaces `@atoms`, `@molecules`, etc.
For example I have two themes based on particle, `theme1` and `theme2` 
if I need to include `@molecules/_header.twig` on the `page.html.twig` of `theme2`, instead of trying to load the molecule from `theme2` folder is trying to load from `theme1` folder.

This is not caused by particle itself, but, is there a workaround to have multiple particle themes installed at the same time? maybe naming as `@mythemeone_atoms` instead of just `@atoms`.

Thanks in advance.

**Comment by hugonaili** [comment]
@juanramonperez Thanks for submitting the issue! This was discussed and addressed internally within the Particle team and we do have a version that is handling multi design systems/themes that will be released in a near future.

**Comment by jryanconklin** [comment]
In the meantime, you can use the following:
* Use the alpha tag version of Component Library: https://www.drupal.org/project/components
* Apply the patch here: https://www.drupal.org/project/components/issues/3027672

This uses configuration for prefixing namespaces at the component module level. Once this version of the module is installed, simply update your components.settings.yml file to allow prefixing. Note that this hasn't been tested yet. The alpha version of the module does not support having unresolvable namespaces in the info.yaml file, so you'll need to delete component-libraries keys that don't have directories (protons, templates, pages).

**Comment by juanramonperez** [comment]
Thank you guys, lets see how it works on the next versions

**Comment by jryanconklin** [comment]
The alpha of https://www.drupal.org/project/components has been released and is our recommended approach for multi-theme in Drupal.
