### ISSUE TITLE
How to specify which design system to build?

### ISSUE THREAD

**Issue by ellyjonez** [phase2/particle#518]
I noticed that Particle can now have multiple design systems in /source/, but I couldn't find anything about how to specify which system to build, or how to use multiple design systems to build multiple apps/themes. Any guidance? Thank you for this great tool.

**Comment by jryanconklin** [comment]
@ellyjonez We've cleared the way to do it, but haven't really come up with a method we're most happy with for documenting how. The simplest way for a Drupal theme at this point is to allow [component library](https://www.drupal.org/project/components) module to prefix namespaces. 

The other route is a long way around in Webpack config / apps. If you have a second set of source files, you'd need to build their own app. We've gone the route of prefixing here for most things, e.g,

* proj-name-1-pl
* proj-name-1-drupal
* proj-name-2-pl
* proj-name-2-drupal

It works, but it does take really digging into the Webpack config in each base app to understand. There's a lot of ways to do it and it depends on the needs of the project.
