### ISSUE TITLE
Enable autoescaping to match Drupal

### ISSUE THREAD

**Issue by andriokha** [phase2/particle#519]
Hi,

I noticed in https://github.com/phase2/particle/commit/4fcc15eb5bee1ba99599c876951643b5b082c752 that autoescaping was switched off. As Drupal has auto-escaping switched on by default we've seen situations where different markup is generated for PL vs Drupal. I could easily be missing something (: but it seems to me that if you want to be able to use the patterns in Drupal you would want to have the same auto-escaping? Alternatively/in addition, it might be worth looking at some package to make dealng with attributes more convenient, such as https://github.com/drupal-pattern-lab/add-attributes-twig-extension? I've got some time to dedicate to this if there's interest in making a change.

Thanks for all your work on the project!

**Comment by jryanconklin** [comment]
If it makes sense for your project, feel free to enable. However closing this issue since 10.4 is moving toward implementing Node Pattern Lab 3 over the PHP version.

**Comment by andriokha** [comment]
Thanks for your time, in the end the project moved away from Drupal so it became a non-issue for us :) I really opened the issue because I was surprised at the default and thought maybe I was missing something.
> closing since 10.4 is moving toward implementing Node Pattern Lab 3 over the PHP version

It's academic for me at this point, but if you're still thinking of supporting Twig, my understanding is that [Node Pattern Lab 3 is planning on using][1] a "traditional" PHP Twig engine as an async renderer, so I think there would still be an autoescape setting? Btw I noticed on that issue that Evan Lovely put into words neatly what was driving me:
> If one is to build an in-depth user interface in an environment that it ultimately will not reside in, there is an understandable amount of fear and hesitation. Why should I build this in Pattern Lab if it won’t work in the CMS? That is a question that can be only put to rest with a confident answer that is basically along the lines of “because it’s compiled the same way”.

Just some thoughts, as I say it's a non-issue for me personally,

Thanks again!

[1]: https://github.com/pattern-lab/the-spec/issues/37
