### ISSUE TITLE
Twig 1.38.4 & Drupal 8.6.13 breaking particle

### ISSUE THREAD

**Issue by BigEdDev** [phase2/particle#529]
We have been using Particle in our sub-theme without issue until the recent update of Drupal core 8.6.13 which breaks the site with the error.

`Twig\Error\SyntaxError: An exception has been thrown during the compilation of a template ("Attribute "name" does not exist for Node "Twig\Node\CheckToStringNode".") in "core/themes/classy`

I can remove {% trans %} from the node.tpl.php add this to the theme and this gets the site running but this is not really a solution to fixing the issue and is just masking the problem.

Some further digging brought me to the file:
https://github.com/phase2/particle/blob/master/source/default/_twig-components/tags/trans.tag.php

This looks to be where the issue is as it looks like the Twig files are copied across from core and extended. Something around the getAttribute('name') in the tag is breaking the theme, Although this is as far as I have got and requires some further investigation.

**Comment by mikecrittenden** [comment]
Similar issue reported here: https://www.drupal.org/project/twig/issues/3045826

**Comment by mikecrittenden** [comment]
And more info here: https://www.drupal.org/project/drupal/issues/3040269

**Comment by mikecrittenden** [comment]
Similar issue reported here: https://www.drupal.org/project/twig/issues/3045826

**Comment by jryanconklin** [comment]
Resolved in #552
