### ISSUE TITLE
Background image urls incorrect in webpack dev server

### ISSUE THREAD

**Issue by tanc** [phase2/particle#541]
When running `dev:pl` the background images in `01-atoms/image/demo/_image-demo.scss` don't resolve and throw 404s. The url produced is not correct and looks like this:
```
http://test.lndo.site:8080/app-pl/pl/patterns/01-atoms-image-demo-image-bg/app-pl/assets/logo.svg?35d56001f631f256cac5758fa7655b6c
```
The correct url (if you edit the path in dev tools it works) should be:
```
http://test.lndo.site:8080/app-pl/assets/logo.svg?35d56001f631f256cac5758fa7655b6c
```

**Comment by tanc** [comment]
Note this only resolves incorrectly in webpack dev server, when compiling normally the url is correct and the images are found.

**Comment by jryanconklin** [comment]
This pattern was overhauled in #570
