### ISSUE TITLE
Uncaught TypeError: enable is not a function

### ISSUE THREAD

**Issue by mstys** [phase2/particle#553]
I'm getting following error
`Uncaught TypeError: enable is not a function`
 running  `npm start` and I can't use JS script.  

Particle version 10.3
Node v8.11.2

I didn't meet this bug in v10.0

**Comment by jryanconklin** [comment]
Hi @mstys! Can you provide some more details about what's going on? Is this a new clone of particle?

**Comment by mstys** [comment]
Hi @jryanconklin . Yest it's new clone of particle. Js function works only outside `enable` function.

**Comment by jryanconklin** [comment]
@mstys Curious! I wonder what happened to your original. Are you blocked from moving forward? If not, I think I'll close this issue. Thank you!

**Comment by mstys** [comment]
@jryanconklin I think that you can close this issue. Thanks for your attention!
