### ISSUE TITLE
Including twig file with object variable breaks Pattern Lab site

### ISSUE THREAD

**Issue by UltCombo** [phase2/particle#566]
I wrote a pattern containing the following line in the twig file:

```twig
{% include '@atoms/_svgicon.twig' with icon %}
```

It works fine in Drupal, but breaks the Pattern Lab site giving an eval error in PHP.

I tried with the demo yml file:

```yml
icon:
  svgname: phone
```

Passing the vars inline from the demo twig does not fix the issue either.

Am I doing something wrong or is this an issue with the PL twig renderer?

**Comment by jryanconklin** [comment]
This pattern has been removed. At a guess, an `icon.svgname` doesn't exist. Try the new version:

https://github.com/phase2/particle/blob/master/source/default/_patterns/01-atoms/svg/_svg--icon.twig
