### ISSUE TITLE
Add more SassDoc annotations

### ISSUE THREAD

**Issue by EvanLovely** [phase2/particle#57]
Would be great if more of our mixins had [SassDoc annotations](http://sassdoc.com/annotations). Upon compile, SassDoc can be viewed at `dest/sassdoc/`.

**Comment by EvanLovely** [comment]
Just added it to the `icon` mixin in 3629335 - check out the awesomeness this generates for us:

![2016-10-06 at 10 16 am](https://cloud.githubusercontent.com/assets/569699/19162770/132c70f6-8bae-11e6-8e76-b7ff38ed5e93.png)

I'm a little unsure of how well the `@link` tag will work as it has to be an absolute link (already tried `../../pattern-lab/public/?p=atoms-icons` with no luck) because that won't work when viewed in a Drupal site locally or on stage... but it'd work for anyone working locally. Better than nothing.

**Comment by grayside** [comment]
Could you pull a base url by environment variable? Thinking a per environment build process can facilitate.

**Comment by EvanLovely** [comment]
I think the only way to do that would be to use our own [SassDoc custom theme](http://sassdoc.com/extending-sassdoc/), which as tempting as it sounds, I don't think we should. I found an alternative workaround by simply linking relatively using Markdown in the description text and it totally works! Done in fb09463 

```diff
+/// See the [Icons in Pattern Lab](../../pattern-lab/public/?p=atoms-icons).
 /// @param {String} $icon - Machine name of icon (filename).
 /// @param {String} $pseudo [before] - `before` | `after` The pseudo element to place the icon in.
 /// @todo Allow `$pseudo: false` to be declared so we don't have to use a pseudo element if we don't want to.
 /// @param {String} $size [inherit]
 /// @param {String} $color [inherit]
 /// @param {Bool} $block [false] - If `display: block` should be applied.
-/// @link http://localhost:3050/pattern-lab/public/?p=atoms-icons
```
