### ISSUE TITLE
Where would reusable functions and other JS live in the project?

### ISSUE THREAD

**Issue by csalmeida** [phase2/particle#581]
I've been adding scripts to it's respective `index.js`. However, where in the file structure can some sort of `global.js` file be added to declare functions that are used across multiple components?

```
/**
 * Card Grid
 */

// Importing custom function.
import { myFunction } from 'global';

import './_card-grid.twig';

export const name = 'card-grid';

export function disable() {}

export function enable() {}

export default enable;
```

I've looked it up in the documentation but could not find a way. Any recommendations would be much appreciated.

**Comment by csalmeida** [comment]
I have created a `index.js` file in `/patterns_source/_global` and added the path to Webpack like so:
```
...
  resolve: {
    alias: {
      themeConfig: path.resolve(__dirname, 'config-themes'),
      global: path.resolve(__dirname, PATH_SOURCE, '_global'),
...
```

**Comment by jryanconklin** [comment]
@csalmeida Howdy! Carousel has a good example:

https://github.com/phase2/particle/blob/master/source/default/_patterns/02-molecules/carousel/index.js

**Comment by jryanconklin** [comment]
Also, answered this before drinking coffee. It depends on your project. I've been including re-usable JS in `protons/utilities/` and that's been working for me.

**Comment by csalmeida** [comment]
Howdy @jryanconklin! Thank you for sharing your thoughts, both very helpful (specially the one after coffee ☕️).
