### ISSUE TITLE
Update Drupal App for 10.4.0

### ISSUE THREAD

**Issue by jryanconklin** [phase2/particle#587]
### Issue

Changes required for Particle 10.4.0 moving to Node PL 3 beta has broken aspects of the default Drupal app.

### Analysis

Updating to Pattern Lab Node 3 made necessary changing several aspects of default patterns. This included updating all patterns to use the full namespaced path of each pattern component. We no longer have access to shorthand component paths. For example:

`@atoms/_card.twig` => `@atoms/card/_card.twig`

Update the Drupal app to include all full names by path and ensure that component libraries default keys work as expected without resorting to gulp to build full namespace keys in `particle.info.yml`. 

### Confirmation

As a developer, I'm able to use Particle as a starter-kit to be provided a version of Pattern Lab Node + Drupal app integration.

**Comment by illepic** [comment]
This should be all set.
