### ISSUE TITLE
Data inheritance not working with twig and yaml

### ISSUE THREAD

**Issue by tonihaupt** [phase2/particle#72]
Hy friends and thanks for this nice pl stack. We have problem getting data inheritance to work.
We have atoms defined with same named .yaml files. Than we include those at?ms inside our molecules, but all the data are gone. Are there some known issues while working with twig(namespaces) and yaml.

**Comment by ensk** [comment]
same problem here. I created a molecule and added data in json/yml format. when view the molecule the data is present, when add the molecule to an organisms the data dissapear. i installed data Inheritance plugin but hasn't work ...any idea? thanks for help

**Comment by ensk** [comment]
inheritance works for me. my mistake was the way to include the pattern. @molecules/path/to/pattern work in patternlab/drupal but hasn't inheritance, the correct way is @molecules-pattern-name

**Comment by tanc** [comment]
@ensk can you provide a more detailed example that works? Did you use any additional plugins?

I have a pattern called site-footer with an associated site-footer.json file containing the value for the variables used in the twig file.

When using the following syntax for my include:
```
{% include "@organisms/site/site-footer/site-footer.twig" %}
```
The inheritance of the variables associated with the embedded twig file (site-footer.json) do not work. I don't see the expected values that I would see if I viewed site-footer.twig on its own.

I tried:

```
{% include "organisms-site-footer" %}
```
That also didn't inherit the variables from site-footer.json

Can you shed any light on this?

**Comment by tanc** [comment]
Ah, I just installed https://github.com/pattern-lab/plugin-php-data-inheritance using:

```cd pattern-lab
composer require pattern-lab/plugin-data-inheritance```

Then edited `config/config.yml`

Added in the plugins section:
```
dataInheritance:
    enabled: true
```

Then I tested my include using the full path method and noted that the data from the included twig file was not inherited. Then I tried the shorthand syntax and confirmed the data *was included*. So thank you @ensk, I can confirm this method works.

**Comment by tanc** [comment]
I also just experimented with https://github.com/aleksip/plugin-data-transform which also allows inheritance but only of shorthand style includes.

That plugin does not need enabling in config.
