### ISSUE TITLE
Template path issue in .theme file on windows

### ISSUE THREAD

**Issue by origindesign** [phase2/particle#88]
Hello, first of all, excellent starter theme, thanks for the hard work!

I have an issue where by the auto generated paths that get added to the .theme file fail for me with with backslashes \ in the path. If i change the setting addToDrupalThemeFile: false and manually change the paths to use a forward slash / then it works fine.

Would this be an issue isolated to windows? Im guessing the setup for this is in p2-theme-core in this function?

function addTwigNamespaceConfigToDrupal(done) {
    const twigNamespaceConfig = getTwigNamespaceConfig(path.dirname(config.drupal.themeFile));
    const drupalThemeFile = yaml.safeLoad(
      fs.readFileSync(config.drupal.themeFile, 'utf8')
    );
    Object.assign(drupalThemeFile['component-libraries'], twigNamespaceConfig);
    const newThemeFile = yaml.safeDump(drupalThemeFile);
    fs.writeFileSync(config.drupal.themeFile, newThemeFile, 'utf8');
    done();
  }

Im happy with manually updating my paths, more of a heads up that this issue arose. Do you see any workaround?

Thanks.

**Comment by illepic** [comment]
Hrm. Windows issues. Node here is trying to use your native filesystem when making these strings. Let me look into having node ignore OS-specific filepathing.

**Comment by illepic** [comment]
@origindesign, i see exactly what's happening: all the node `path` functions are trying to write os-specific pathing when they SHOULD be writing forward slashes regardless. Let's see what flags we can pass to `path` functions to possibly ignore the OS.

Even though we rewrote this entire feature in v10, we're probably still going to be affected by it. I'm tagging this as a v9 and v10 issue.

**Comment by illepic** [comment]
Noting here:

1. to fix in v9 requires updates to https://github.com/phase2/p2-theme-core/
1. to fix in v10 requires updates to https://github.com/phase2/pattern-lab-starter/blob/epic/v10/tools/tasks/gulp-twig-namespaces.js

**Comment by illepic** [comment]
Before writing paths to yaml, we'll need to disassemble and rejoin with specific separators: https://stackoverflow.com/a/30318335
