### ISSUE TITLE
Rename Master Branch

### ISSUE THREAD

**Issue by jryanconklin** [phase2/particle#899]

**Comment by dslemay** [comment]
I fully support this. The [fetch-particle](https://github.com/phase2/create-particle/blob/master/index.js#L31) will not have breaking changes with this moving forward since it fetches the latest tags and doesn't care for branch naming conventions.

**Comment by illepic** [comment]
Will tweak the travis file to handle this, thoughts on name? I vote `primary`.

**Comment by dslemay** [comment]
`main` seems to be a common pattern I have seen in various discussions on the topic.

**Comment by jryanconklin** [comment]
I support either. Main might be nice if consensus is already built around it. But I’m happy with any change.

**Comment by dslemay** [comment]
`main` is the example given in the Git 2.28 [announcement](https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch) on the `init.defaultBranch` flag as well. I too am fine either way and would be happy for the change. Personally I would lean towards `main`.

**Comment by jryanconklin** [comment]
This has been completed!
